CONTRIBUTING.md
Fixed some typos and grammar in ` CONTRIBUTING.md `.
=> Proof read CONTRIBUTING.md

.eslintrc.js, .idea/react-auth-kit.iml, src/AuthProvider.tsx, src/PrivateRoute.tsx, src/higherOrderComponents/withAuthHeader.tsx, src/higherOrderComponents/withAuthUser.tsx, src/higherOrderComponents/withIsAuthenticated.tsx, src/higherOrderComponents/withSignIn.tsx, src/higherOrderComponents/withSignOut.tsx
=> fixed: All eslint error

package.json, src/TokenObject.ts, src/hooks/useAuth.ts, src/hooks/useAuthHeader.ts, src/hooks/useAuthUser.ts, src/hooks/useIsAuthenticated.ts, src/hooks/useSignIn.ts, src/hooks/useSignOut.ts
=> fix: More ESLint errors

package.json, src/hooks/useAuth.ts, src/hooks/useAuthHeader.ts, src/hooks/useAuthUser.ts, src/hooks/useIsAuthenticated.ts, src/hooks/useSignIn.ts, src/hooks/useSignOut.ts
=> docs : add documentation for hook functions #67

src/hooks/useAuth.ts, src/hooks/useAuthHeader.ts, src/hooks/useAuthUser.ts
=> Fix hooks 'useAuthheader' and 'useAuthUser'

src/higherOrderComponents/withAuthHeader.tsx, src/higherOrderComponents/withAuthUser.tsx, src/higherOrderComponents/withIsAuthenticated.tsx, src/higherOrderComponents/withSignIn.tsx, src/higherOrderComponents/withSignOut.tsx
=> docs : add function doc for higherOrderComponent

CONTRIBUTING.md
=> Created guideline for contributing to documentation

CONTRIBUTING.md, docs/contributing.md, mkdocs.yml
=> Moved docs contrib guide to new page in docs.

docs/authdata.md, docs/authheader.md, docs/checkauth.md, docs/contributing.md, docs/index.md, docs/installation.md, docs/privateroute.md, docs/refreshtoken.md, docs/robots.txt, docs/signin.md, docs/signout.md, docs/usage.md, mkdocs.yml, src/RefreshToken.ts, src/higherOrderComponents/withRefreshToken.tsx, src/hooks/useRefreshToken.ts, src/index.tsx
=> Add Refresh token Feature

package-lock.json, package.json, src/TokenObject.ts
=> Issue of getting fake cookies

.husky/commit-msg, commitlint.config.js, package-lock.json, package.json
=> Adding git linting

docs/checkauth.md
=> Update to checkauth.me

README.md
=> Docs : updated and fixed typos

src/__tests__/utils/reducers.test.ts, src/utils/reducers.ts
These changes will solve issue #578
I removed lines 55 and 56 of reducers.ts since that is unreachable code in the application's current state. It can be added back if needed, but it helped bring the test coverage up and should not affect the desired performance of the application as a whole. 
I also added a test suite that covers both utils/actions.ts and utils/reducers.ts. The tests are in one file, \_\_tests_\_\/utils/reducers.test.ts since it did not make sense to me to create a test suite just for actions (which are all a bunch of interfaces and no functions). See this screenshot for test coverage statistics:
=> Add actions / reducers unit tests

src/__tests__/TokenObject.test.ts
=> Add Unit Test Case for TokenObject.ts #577 

CONTRIBUTING.md, package-lock.json
=> Conventional commits in Contributing.md #588

.github/pull_request_template.md
Update to the `pull_request_template.md` that adds more details.
Please let me know if this format is ok or if anything needs to change.
Thank you!
Fixes #594
=> refactor: edited the pull_request_template.md

docs/refreshtoken.md
#649 
Correct spelling of `return` in [refreshtoken.md](https://github.com/react-auth-kit/react-auth-kit/blob/master/docs/refreshtoken.md) doc.
=> docs: correct spelling of return

src/__tests__/hooks/useAuthHeader.test.tsx, src/__tests__/hooks/useAuthUser.test.tsx, src/__tests__/hooks/useIsAuthenticated.test.tsx, src/__tests__/hooks/useSignIn.test.tsx, src/__tests__/hooks/useSignOut.test.tsx
Fixes #663
Added tests for the hooks
=> test: add hooks tests

package-lock.json, package.json
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>
=> fix(package.json): updated linting package

CHANGELOG.md, package-lock.json, package.json, src/AuthProvider.tsx, src/__tests__/AuthProvider.test.tsx, src/types.ts
=> Release to Master

src/higherOrderComponents/withSignIn.tsx, src/hooks/useSignIn.ts, src/types.ts
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>
Fixes: #680
=> fix: signing param authState is now optional

package-lock.json, package.json, src/PrivateRoute.tsx, src/__tests__/AuthProvider.test.tsx, src/__tests__/PrivateRoute.test.tsx, src/index.tsx
BREAKING CHANGE: The PrivateRoute.tsx Option will not available for now.
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>
=> perf(privateRoute): updated to react router v6

examples/create-react-app-refresh-token/package-lock.json, examples/create-react-app-refresh-token/package.json, examples/create-react-app-refresh-token/src/App.js, examples/create-react-app-refresh-token/src/Routes.js, examples/create-react-app-refresh-token/src/components/Home.js, examples/create-react-app-refresh-token/src/components/Login.js, examples/create-react-app/package-lock.json, examples/create-react-app/package.json, examples/create-react-app/src/App.js, examples/create-react-app/src/Routes.js, examples/create-react-app/src/components/Home.js, examples/create-react-app/src/components/Login.js
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>
=> fix(examples): updated examples as per needed

.markdownlint.json, docs/authdata.md, docs/authheader.md, docs/checkauth.md, docs/contributing.md, docs/index.md, docs/installation.md, docs/integration.md, docs/privateroute.md, docs/refreshtoken.md, docs/signin.md, docs/signout.md, docs/update.md, package-lock.json, package.json
Implemented markdownlint to lint the docs folder, added the package itself & 2 scripts to the package.json to be able to lint & fix with markdownlint
=> feat(docs): add markdownlint

mkdocs.yml
=> feat: added dar theme in the theme

.markdownlint.json, docs/docs_overrides/main.html, docs/index.md, docs/installation.md, docs/integration.md, docs/signin.md, mkdocs.yml
=> Updated the Docs

commitlint.config.js, src/AuthProvider.tsx, src/TokenObject.ts
=> Code Style Fixing

README.md, docs/index.md
=> fix(docs): updated readme

docs/authdata.md, docs/authheader.md, docs/checkauth.md, docs/integration.md, docs/privateroute.md, docs/refreshtoken.md, docs/signin.md, docs/signout.md, mkdocs.yml
=> Description-add

docs/signin.md
Please answer the following questions for yourself before submitting an issue.
**Description**\
I have noticed that on the sign in page, in the last section the links to the _refresh token_ page do **not** work as they should so I propose this change in the documentation.
=> docs: edit the signin.md

docs/refreshtoken.md, examples/create-react-app-refresh-token/package-lock.json, examples/create-react-app-refresh-token/package.json, examples/create-react-app-refresh-token/src/refreshApi.js, src/AuthProvider.tsx, src/__tests__/AuthProvider.test.tsx
=> Refresh token

docs/docs_overrides/main.html
=> fix: ads not visiable in pages

CHANGELOG.md, package-lock.json, package.json, rollup.config.mjs, tsconfig.json
=> Tree Stacking

CHANGELOG.md, package-lock.json, package.json, src/__tests__/hooks/useIsAuthenticated.test.tsx, src/higherOrderComponents/withIsAuthenticated.tsx, src/hooks/useIsAuthenticated.ts
IsAuthenticated hooks and HOC is making infinity rendering
=> isAuthenticated Infinity loop

package.json
=> refactor: updated lint-staged command

docs/privateroute.md
Add import ```Routes``` (to prevent naming conflicts)
Rename Component to ```Router```
=> Edit some code in privateroute

README.md, docs/getting_started/index.md
N/A – Adding Clerk.com sponsorship
=> Add sponsorship for Clerk.com

docs/index.md
N/A – adds Clerk callout to docs homepage
=> feat(docs): add clerk callout to docs homepage
